### ISSUE TITLE
Not working on Android 5.1.1

### ISSUE THREAD

**Issue by Eledar** [rameshvoltella/RWeekCalendar#1]
Hello, can you make it working on Android 5.1.1? It's amazing calendar but without compatibility with Android 5.1.1 it's useless. :-/

**Comment by rameshvoltella** [comment]
what is the error?

**Comment by Eledar** [comment]
![screen](https://cloud.githubusercontent.com/assets/12599792/10717539/c38c79e6-7b5b-11e5-8f23-b8f2977d09fd.png)

This happens every time I try to run the application on virtual device (Genymotion - 5.1.1) and even real phone (iNew V3 with Cyanogenmod 12.1 - 5.1.1). Everything works on virtual 4.4.4. I tried your demo app on Sony Xperia Z2 with 5.1.1 and I don't really know what's wrong...

**Comment by Eledar** [comment]
Is there any possibility to make it work? 
UPDATE: I tried your demo app on iNew V3 (5.1.1), Honor 3C (4.4.2), Redmi 2 (4.4.4), Genymotion (5.1.1, 4.3, 4.2.2) and only one phone where it works is Xperia Z2(5.1.1).

**Comment by rameshvoltella** [comment]
okey i was busy will fix asap

**Comment by Eledar** [comment]
So how is it going? :)

**Comment by rameshvoltella** [comment]
Buddy i have tested in many devices but i cant find the bug. Also i dont see the Genymotion 5.1.1 AVD in Genymotion emulator, but from your log i made a fix better u test the build and comment whether bug remain or not

**Comment by Eledar** [comment]
I tried it again and it crash with "t.commit();", without it app normally working. (calendar of course not working without it)

**Comment by rameshvoltella** [comment]
can you post the log

**Comment by Eledar** [comment]
It look still same (now it's with my app) ![error1](https://cloud.githubusercontent.com/assets/12599792/11004449/9e956b50-84b8-11e5-9930-c46708376eee.png)

**Comment by rameshvoltella** [comment]
buddy the log seems to error from your app, please run the calender app separately so that we can test it.  if your setting the custum attribute like  args.putString(RWeekCalendar.DATE_SELECTOR_BACKGROUND,"bg_select");//set background to the selected dates

  args.putString(RWeekCalendar.NOW_BACKGROUND,"bg_now");

here bg_now and bg_select is not just a string value its the drawable xml for setting the corresponding views please check the code and run app seperatly :)

**Comment by Eledar** [comment]
Can you send me your working app? I'll try it...

**Comment by rameshvoltella** [comment]
just pull the repo and run i have updated repo with a fix.

**Comment by Eledar** [comment]
It's working now. :O so...i have to find what's wrong in my app...thank you :)

**Comment by rameshvoltella** [comment]
okey Thank you for the bug report  :)
