### ISSUE TITLE
Conflict in gradle

### ISSUE THREAD

**Issue by krunal09** [rameshvoltella/RWeekCalendar#3]
While importing this project , i m getting a following error at the time of compilation:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/joda/time/Chronology;

There is a conflict between JodaAndroidTime & joda-time.
 compile 'net.danlew:android.joda:2.9.0'
 compile 'joda-time:joda-time:2.8.2' in gradle 

I m using compile 'net.danlew:android.joda:2.9.0' for 
    //Initializing JodaTime
        JodaTimeAndroid.init(mContext);

**Comment by rameshvoltella** [comment]
The joda file used in the main library is compile 'net.danlew:android.joda:2.8.1' if you check https://github.com/rameshvoltella/RWeekCalendar/blob/master/RamzCalSample/ramzcalender/build.gradle

link you can find,  this is the problem for the conflict, i dont think you need to add joda lib in your main gridle file again. 
If you want to use your joda lib just replace the joda library compile line  from the main calender gradle and replace it with yours.
