### ISSUE TITLE
Past date selection

### ISSUE THREAD

**Issue by Asha-Nellaiappan** [rameshvoltella/RWeekCalendar#4]
I am new to github.

If i select past date it wouldn't set into text view.

Is your calendar view is only for present and future dates? or am i understand anything wrong about your calendar view?

![device-2016-04-29-153753](https://cloud.githubusercontent.com/assets/18715120/14913647/4584ddc2-0e22-11e6-8d10-eb84d102d69a.png)

![device-2016-04-29-153937](https://cloud.githubusercontent.com/assets/18715120/14913654/526a77ae-0e22-11e6-93ef-eaf9e8848d6c.png)

First image i choose date as mar 24/2012 press done.

The text view set date as 24-4-2016 in second image.

if i understand anything wrong please guide me.

**Comment by rameshvoltella** [comment]
@Asha-Nellaiappan so sorry for a late replay, its just the picker issue i had used some open sourse picker for example u can use your custom picker or any thing also i have add a fix to go to previous date see commit f28f9b0
