### ISSUE TITLE
is there a way to set current date as first display at calendar .. thanks :D

### ISSUE THREAD

**Issue by ZybreanaZin** [rameshvoltella/RWeekCalendar#5]

**Comment by AndroidSources** [comment]
did you find a solution for this question?

**Comment by rameshvoltella** [comment]
Right now am busy with some other work will fix this asap when i complete my current task.

**Comment by AndroidSources** [comment]
thank you for the reply

**Comment by rameshvoltella** [comment]
@AndroidSources @ZybreanaZin  update is comming soon :)

**Comment by AndroidSources** [comment]
@rameshvoltella Thanks a lot man. This Calendar was really cool. That was the only issue i faced.

**Comment by rameshvoltella** [comment]
@AndroidSources  hi a fix has added see commit f28f9b0 and new read me   Happy Xmas

**Comment by AndroidSources** [comment]
@rameshvoltella  In the normal calendar No date is reflected for the first time when im clicking . It always shows the current date. . Once the date picker is used once it works normally.Can you please look into this
