### ISSUE TITLE
No date is reflected for the first time when im clicking 

### ISSUE THREAD

**Issue by AndroidSources** [rameshvoltella/RWeekCalendar#6]
No date is reflected for the first time when i'm clicking . It always shows the current date.Can you please look into this. it works perfectly with date pickers but nothing happens when the day is clicked in weekview

**Comment by rameshvoltella** [comment]
@AndroidSources will get back to you soon :)

**Comment by rameshvoltella** [comment]
@AndroidSources is that only with the current week only right, like if you scroll to next week you can do this right?

**Comment by AndroidSources** [comment]
@rameshvoltella  Yeah. It is only with current week . Thanks for your quick reply

**Comment by rameshvoltella** [comment]
@AndroidSources a fix has added  check the new apk from readme file please close the issue if you got the solution

**Comment by AndroidSources** [comment]
Thanks for fixing this @rameshvoltella . This weekpicker is lot helpful.
