### ISSUE TITLE
setting background color for now and selected date.

### ISSUE THREAD

**Issue by ManuBabu** [rameshvoltella/RWeekCalendar#7]
Hi @rameshvoltella, 
i am trying to customize background color for current date and selected date item, 
since the parameter we need to pass is string , i tried these things didn't worked for me.
1. args.putString(RWeekCalendar.DATE_SELECTOR_BACKGROUND, "90A4AE");
1. args.putString(RWeekCalendar.DATE_SELECTOR_BACKGROUND, "#90A4AE");
1. args.putString(RWeekCalendar.DATE_SELECTOR_BACKGROUND, "now_background_olor");// name of color variable in R file.

Please clarify me what parameter to pass for this instruction.
Thanks

**Comment by antoniomerlin** [comment]
By using this above argument u can only change the color of circular drawable representing selected date;
`args.putString(RWeekCalendar.DATE_SELECTOR_BACKGROUND, "bg_green");`
