### ISSUE TITLE
Is there a way to start the week on Monday instead of Sunday?

### ISSUE THREAD

**Issue by ibanomni** [rameshvoltella/RWeekCalendar#9]
In the european callendar the first day of the week is monday. How can I change to set the first day of week on Monday?

**Comment by rameshvoltella** [comment]
i need to change the code because ri8 now custom date first not support will add this asap

**Comment by ibanomni** [comment]
I manage to make it myself so there is no need to do it at least for me. Anyway I think it will be great for other people who has this problem. 

What is really important is to change this peace of code in CalUtil class. 

`int weekGap = CalUtil.mDateGap(currentDateTime.dayOfWeek().getAsShortText(Locale.ENGLISH).substring(0, 3).toLowerCase());`

If you don't put Locale.ENGLISH and the device is not in english it won't work properly. 

And thanks for the amazing work! your week calendar is really well done!

**Comment by rameshvoltella** [comment]
thank happy u able to solve it
